server:
  port: 8080

spring:
  application:
    name: spring-ai-source-notes
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    io.github.iweidujiang.springaisourcenotes.advisor: INFO
    org.springframework.ai: DEBUG
    org.springframework.ai.chat.client: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai.model.tool: DEBUG
